language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

env:
  - CONSUMER_DIR=consumer
  - PROVIDER_DIR=provider

script:
  - cd $CONSUMER_DIR && ./gradlew clean
  - cd $CONSUMER_DIR && ./gradlew test
  - cd $PROVIDER_DIR && ./gradlew clean
